In [1]:
# 1.Array Creation
# Create a 3D array of shape (4, 5, 6) filled with consecutive integers starting from 1. Generate an array with random floats sampled from a normal distribution with mean 10
# and standard deviation 5, shape (10, 10). 
# Create a 2D array of shape (8, 8) where the diagonal elements are 1 and others are 0.

# 2. Operations
# Perform element-wise multiplication and division between two randomly generated arrays
# of the same shape. Multiply a 2D array by a 1D array using broadcasting rules and explain the result. Compute the dot product and matrix multiplication of two compatible matrices using
# np.dot and @ operator.

# 3. Indexing & Slicing
# Given a 2D array of shape (10, 10), use advanced integer indexing to extract elements at
# random row and column indices, including duplicate indices. Extract a sub-array excluding the border rows and columns (i.e., inner (8, 8) block).
# Reverse the rows of a matrix without changing the columns using slicing.

# 4. Reshaping & Manipulating Arrays
# Reshape a (100,) array into (10, 10) and then flatten it back, verifying the integrity of the
# data. Concatenate three arrays along different axes; demonstrate horizontal and vertical
# stacking with appropriate code. Split a (12, 12) matrix vertically into 3 equal parts using NumPy splitting functions.

# 5. Aggregation Functions
# Calculate the mean, median, and standard deviation of each column in a (15, 10) array. 
# Find the indices of minimum and maximum values along each row.
# Compute the cumulative sum and cumulative product of elements along the flattened array.

# 6. Handling Missing Values
# Create an array of 200 random floats and randomly assign 10% of values to np.nan.
# Write code to detect and count the missing values. Replace missing values with the mean of their respective columns.
# Demonstrate removing rows or columns containing any missing values

In [2]:
import numpy as np

In [4]:
# 1.

arr_3d = np.arange(1, 4*5*6 + 1).reshape(4, 5, 6)
print("3D Array (4,5,6):\n", arr_3d)


3D Array (4,5,6):
 [[[  1   2   3   4   5   6]
  [  7   8   9  10  11  12]
  [ 13  14  15  16  17  18]
  [ 19  20  21  22  23  24]
  [ 25  26  27  28  29  30]]

 [[ 31  32  33  34  35  36]
  [ 37  38  39  40  41  42]
  [ 43  44  45  46  47  48]
  [ 49  50  51  52  53  54]
  [ 55  56  57  58  59  60]]

 [[ 61  62  63  64  65  66]
  [ 67  68  69  70  71  72]
  [ 73  74  75  76  77  78]
  [ 79  80  81  82  83  84]
  [ 85  86  87  88  89  90]]

 [[ 91  92  93  94  95  96]
  [ 97  98  99 100 101 102]
  [103 104 105 106 107 108]
  [109 110 111 112 113 114]
  [115 116 117 118 119 120]]]


In [5]:
arr_normal = np.random.normal(10, 5, size=(10, 10))
print("\nNormal Dist Array (10,10):\n", arr_normal)


Normal Dist Array (10,10):
 [[13.87687929  8.70515136  8.66163197  2.4579763  12.74228529 13.22054744
   6.26332222  8.09881808  5.75303649  7.20633093]
 [16.40682337 12.38307756 -2.70887021  6.99591215 10.81940605  7.69266973
   2.31316671  7.64194614 15.56301071  6.18583784]
 [ 9.57970098  8.0351072  16.64794305 15.03249147  7.95028624 13.59694113
   8.00385848  8.18886736 11.73665177  9.29649416]
 [12.60752949  6.0948511  12.51689803  9.65123284 12.51407855  4.18593898
   4.24499038 16.65247049 11.05673401 18.74785941]
 [16.90186718 11.99779843  4.24443054 11.45113719  8.57136367  3.5754391
  11.01541929 15.58494354 11.10709751  3.56206547]
 [ 7.81908908 14.24006898  4.11939806 14.53010582 20.57463633  9.28437735
  12.20995836  9.79171144 18.01668146 12.46222356]
 [ 3.31199235 -0.73736643  8.91376409  8.47321109  5.84551179 13.69127019
   7.10847771 15.18648576 13.03062559  6.82133178]
 [11.55955955  3.35004694  4.58522282 13.33529518  9.41474046  6.99109178
   4.92325839  6.478568

In [7]:
arr_diag = np.eye(8)
print("\n 8x8 Diagonal Array:\n", arr_diag)


 8x8 Diagonal Array:
 [[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [8]:
#2.

A = np.random.randint(1, 10, (4, 4))
B = np.random.randint(1, 10, (4, 4))

print("\nElement-wise Multiplication:\n", A * B)
print("\nElement-wise Division:\n", A / B)


Element-wise Multiplication:
 [[45 48 49 10]
 [81 12  6 35]
 [16  2  7 54]
 [56 18 18 12]]

Element-wise Division:
 [[1.8        0.75       1.         0.4       ]
 [1.         0.75       6.         1.4       ]
 [4.         2.         7.         0.66666667]
 [1.14285714 0.5        4.5        0.33333333]]


In [9]:
mat_2d = np.arange(12).reshape(3, 4)
vec_1d = np.array([1, 2, 3, 4])

broadcast_result = mat_2d * vec_1d
print("\nBroadcasting Result (2D * 1D):\n", broadcast_result)
print("\nExplanation: Each row of mat_2d is multiplied by the 1D array.")


Broadcasting Result (2D * 1D):
 [[ 0  2  6 12]
 [ 4 10 18 28]
 [ 8 18 30 44]]

Explanation: Each row of mat_2d is multiplied by the 1D array.


In [10]:
X = np.random.randint(1, 10, (3, 2))
Y = np.random.randint(1, 10, (2, 3))

print("\nDot Product:\n", np.dot(X, Y))
print("\nMatrix Multiplication using @:\n", X @ Y)


Dot Product:
 [[27 35 35]
 [51 60 60]
 [30 37 37]]

Matrix Multiplication using @:
 [[27 35 35]
 [51 60 60]
 [30 37 37]]


In [11]:
# 3.

arr10 = np.arange(100).reshape(10, 10)

rows = np.random.choice(10, 5)
cols = np.random.choice(10, 5)
adv_selected = arr10[rows, cols]

print("\nAdvanced Indexed Elements:\n", adv_selected)


Advanced Indexed Elements:
 [11 56 56  5 63]


In [12]:
inner_8x8 = arr10[1:-1, 1:-1]
print("\nInner 8x8 Block:\n", inner_8x8)


Inner 8x8 Block:
 [[11 12 13 14 15 16 17 18]
 [21 22 23 24 25 26 27 28]
 [31 32 33 34 35 36 37 38]
 [41 42 43 44 45 46 47 48]
 [51 52 53 54 55 56 57 58]
 [61 62 63 64 65 66 67 68]
 [71 72 73 74 75 76 77 78]
 [81 82 83 84 85 86 87 88]]


In [13]:
rev_rows = arr10[::-1, :]
print("\nRows Reversed (Columns Same):\n", rev_rows)


Rows Reversed (Columns Same):
 [[90 91 92 93 94 95 96 97 98 99]
 [80 81 82 83 84 85 86 87 88 89]
 [70 71 72 73 74 75 76 77 78 79]
 [60 61 62 63 64 65 66 67 68 69]
 [50 51 52 53 54 55 56 57 58 59]
 [40 41 42 43 44 45 46 47 48 49]
 [30 31 32 33 34 35 36 37 38 39]
 [20 21 22 23 24 25 26 27 28 29]
 [10 11 12 13 14 15 16 17 18 19]
 [ 0  1  2  3  4  5  6  7  8  9]]


In [14]:
# 4. 

arr100 = np.arange(100)
arr10x10 = arr100.reshape(10, 10)
flat_again = arr10x10.flatten()

print("\nIntegrity Check:", np.array_equal(arr100, flat_again))


Integrity Check: True


In [15]:
a1 = np.ones((3, 3))
a2 = np.zeros((3, 3))
a3 = np.full((3, 3), 5)

concat_axis0 = np.concatenate((a1, a2, a3), axis=0)  # vertical
concat_axis1 = np.concatenate((a1, a2, a3), axis=1)  # horizontal

print("\nConcatenated Axis 0:\n", concat_axis0)
print("\nConcatenated Axis 1:\n", concat_axis1)

# Horizontal & Vertical Stack
print("\nHorizontal Stack:\n", np.hstack((a1, a2)))
print("\nVertical Stack:\n", np.vstack((a1, a2)))


Concatenated Axis 0:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]

Concatenated Axis 1:
 [[1. 1. 1. 0. 0. 0. 5. 5. 5.]
 [1. 1. 1. 0. 0. 0. 5. 5. 5.]
 [1. 1. 1. 0. 0. 0. 5. 5. 5.]]

Horizontal Stack:
 [[1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]]

Vertical Stack:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [16]:
mat12 = np.arange(144).reshape(12, 12)
split_vertical = np.split(mat12, 3, axis=1)

print("\nVertical Splits (12x12 → Three 12x4):")
for i, part in enumerate(split_vertical):
    print(f"\nPart {i+1}:\n", part)


Vertical Splits (12x12 → Three 12x4):

Part 1:
 [[  0   1   2   3]
 [ 12  13  14  15]
 [ 24  25  26  27]
 [ 36  37  38  39]
 [ 48  49  50  51]
 [ 60  61  62  63]
 [ 72  73  74  75]
 [ 84  85  86  87]
 [ 96  97  98  99]
 [108 109 110 111]
 [120 121 122 123]
 [132 133 134 135]]

Part 2:
 [[  4   5   6   7]
 [ 16  17  18  19]
 [ 28  29  30  31]
 [ 40  41  42  43]
 [ 52  53  54  55]
 [ 64  65  66  67]
 [ 76  77  78  79]
 [ 88  89  90  91]
 [100 101 102 103]
 [112 113 114 115]
 [124 125 126 127]
 [136 137 138 139]]

Part 3:
 [[  8   9  10  11]
 [ 20  21  22  23]
 [ 32  33  34  35]
 [ 44  45  46  47]
 [ 56  57  58  59]
 [ 68  69  70  71]
 [ 80  81  82  83]
 [ 92  93  94  95]
 [104 105 106 107]
 [116 117 118 119]
 [128 129 130 131]
 [140 141 142 143]]


In [17]:
# 5. 

arr_15x10 = np.random.randint(1, 100, (15, 10))

mean_cols = np.mean(arr_15x10, axis=0)
median_cols = np.median(arr_15x10, axis=0)
std_cols = np.std(arr_15x10, axis=0)

print("\nColumn Means:\n", mean_cols)
print("\nColumn Medians:\n", median_cols)
print("\nColumn Std:\n", std_cols)


Column Means:
 [56.2        51.2        43.86666667 40.66666667 42.53333333 59.6
 55.06666667 53.6        45.73333333 55.4       ]

Column Medians:
 [62. 51. 42. 42. 28. 66. 52. 50. 47. 52.]

Column Std:
 [28.20921835 24.28497478 31.01153907 24.97643334 32.06424107 29.19771681
 26.42086717 30.10382036 22.11625847 25.21851172]


In [18]:
min_idx = np.argmin(arr_15x10, axis=1)
max_idx = np.argmax(arr_15x10, axis=1)

print("\nMin Indices per Row:\n", min_idx)
print("\nMax Indices per Row:\n", max_idx)


Min Indices per Row:
 [2 9 4 3 2 4 3 3 1 1 2 7 0 2 5]

Max Indices per Row:
 [9 1 0 9 5 6 7 6 9 8 3 0 5 5 6]


In [23]:
flat = arr_15x10.flatten()
print("\nCumulative Sum:\n", np.cumsum(flat))
print("\nCumulative Product:\n", np.cumprod(flat))


Cumulative Sum:
 [  62  139  153  225  250  320  355  392  465  545  569  667  733  775
  803  893  965 1058 1080 1094 1182 1247 1269 1341 1345 1377 1405 1430
 1468 1555 1638 1664 1723 1743 1837 1915 2009 2092 2116 2215 2235 2284
 2290 2296 2304 2402 2444 2538 2594 2635 2667 2725 2774 2796 2803 2816
 2885 2926 2978 3000 3064 3076 3172 3180 3271 3314 3351 3449 3508 3579
 3676 3758 3795 3814 3840 3933 4032 4073 4129 4170 4253 4289 4368 4417
 4500 4551 4620 4670 4710 4799 4845 4848 4890 4934 5011 5057 5116 5189
 5284 5336 5390 5438 5450 5538 5584 5650 5702 5766 5813 5858 5937 5990
 6000 6072 6088 6124 6162 6165 6232 6296 6314 6373 6450 6492 6571 6658
 6695 6765 6783 6839 6850 6901 6903 6920 6960 7048 7051 7069 7086 7135
 7217 7268 7355 7392 7406 7409 7501 7515 7537 7558]

Cumulative Product:
 [                  62                 4774                66836
              4812192            120304800           8421336000
         294746760000       10905630120000      796110998760000
    63

In [20]:
# 6.

arr = np.random.random(200)
nan_count = int(0.10 * len(arr))
nan_indices = np.random.choice(len(arr), nan_count, replace=False)
arr[nan_indices] = np.nan

print("\nTotal Missing Values:", np.isnan(arr).sum())


Total Missing Values: 20


In [21]:
mean_value = np.nanmean(arr)
arr_filled = np.where(np.isnan(arr), mean_value, arr)

print("\nMissing After Filling:", np.isnan(arr_filled).sum())


Missing After Filling: 0


In [22]:
arr_no_nans = arr[~np.isnan(arr)]
print("\nArray After Removing NaNs (size):", arr_no_nans.size)


Array After Removing NaNs (size): 180
